[colors]
ansi = [
    '000000',
    '000000',
    '000000',
    '000000',
    '00BFFF', # command
    '000000',
    'FF8200', # 옵션
    '000000',
]
# background = '000000'
brights = [
    '3FFF00', # 추천 글씨
    'FC0FC0', # 이미 친 글씨
    'FFFFFF',
    'FFFFFF',
    'FFFFFF',
    'FFFFFF',
    'FFFFFF',
    'FFFFFF',
]
cursor_bg = '7CFC00'
cursor_border = '7CFC00'
cursor_fg = '000000'
foreground = 'E0F7FA'
selection_bg = '85B09A'
selection_fg = 'FFA0A0'

[colors.indexed]

[metadata]
author = 'peco (https://github.com/treetea-bro)'
name = 'PecoArcade'